import React from "react"
import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { LocaleProvider } from "@/lib/i18n/locale-context";
import { AuthProvider } from "@/lib/auth-context";

import "./globals.css";

const _inter = Inter({ subsets: ["latin", "cyrillic"] });
const _jetbrainsMono = JetBrains_Mono({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: {
    default: "AI Text Detector",
    template: "%s | AI Text Detector",
  },
  description:
    "Automated system for detecting texts generated by artificial intelligence models, with a focus on Russian and Kazakh language corpora.",
};

export const viewport: Viewport = {
  themeColor: "#0a0c10",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="font-sans antialiased min-h-screen">
        <AuthProvider>
          <LocaleProvider>
            {children}
            <Toaster />
          </LocaleProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
