/**
 * Application-wide constants and configuration values.
 */

export const APP_NAME = "AI Text Detector";

export const APP_DESCRIPTION =
  "Automated system for detecting texts generated by artificial intelligence models, with a focus on Russian and Kazakh language corpora.";

export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL || "/api";

export const MAX_TEXT_LENGTH = 50_000;
export const MIN_TEXT_LENGTH = 50;
export const MAX_FILE_SIZE_MB = 10;
export const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;

export const ACCEPTED_FILE_TYPES = [
  "text/plain",
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
] as const;

export const ACCEPTED_FILE_EXTENSIONS = ".txt,.pdf,.docx";

export const SUPPORTED_LANGUAGES = [
  { value: "auto", label: "Auto-detect" },
  { value: "ru", label: "Russian" },
  { value: "kk", label: "Kazakh" },
  { value: "en", label: "English" },
] as const;

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  ANALYZE: "/dashboard/analyze",
  RESULTS: "/dashboard/results",
  PROFILE: "/dashboard/profile",
  HISTORY: "/dashboard/history",
} as const;

export const AUTH_TOKEN_KEY = "auth_token";
export const REFRESH_TOKEN_KEY = "refresh_token";
